name: docking_env
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.8
  - rdkit=2020.09.5
  - numpy=1.19.2
  - pandas=1.1.5
  - matplotlib=3.3.2
  - scipy=1.5.2
  - pymol-open-source=2.4.1
